version: 3
admin_access: true
replicas:
  minimum: 1
  maximum: 1
resources:
  requests:
    memory: 128m
ports:
  - target_port: 5000
healthchecks:
  liveness:
    http:
      path: /healthz
config:
  volume: true
metrics:
  prometheus:
    path: /internal-backstage/prometheus
